/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        // Copy and paste your answer from CodingBat appropriatley here.
        return false;
    }
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        return -1;
    }
}
