/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

import org.junit.Test;
import static org.junit.Assert.*;

public class GoogleBillboardTest {
    @Test public void isPrimeCorrect() {
        GoogleBillboard classUnderTest = new GoogleBillboard();
        assertEquals(classUnderTest.isPrime(2), true);
        assertEquals(classUnderTest.isPrime(3), true);
        assertEquals(classUnderTest.isPrime(4), false);
        assertEquals(classUnderTest.isPrime(5), true);
        classUnderTest.isPrime(0);
    }
    @Test public void first10DigitPrimeInETest() {
        String e = "27182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274274663919320030599218174135966290435";
        GoogleBillboard classUnderTest = new GoogleBillboard();
        System.out.println(classUnderTest.firstPrimeNumberIn(e));
        assertEquals(classUnderTest.firstPrimeNumberIn(e), 7427466391L);
    }
}
